# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 21:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import djgeojson.fields
import miroutes.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_grade_system', models.IntegerField(choices=[(0, b'France'), (1, b'UIAA'), (2, b'UK'), (3, b'Sierra')], default=1)),
                ('area_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=100)),
                ('country_code', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_name', models.CharField(max_length=100)),
                ('route_grade', models.CharField(blank=True, max_length=4, null=True)),
                ('route_rating', models.IntegerField(choices=[(1, b'poor'), (2, b'ok'), (3, b'not bad'), (4, b'good'), (5, b'excellent')], default=b'1')),
                ('route_length', models.IntegerField(blank=True, null=True)),
                ('route_first_ascent', models.CharField(blank=True, max_length=100, null=True)),
                ('route_number_of_bolts', models.IntegerField(blank=True, null=True)),
                ('route_security_rating', models.IntegerField(default=3)),
                ('route_description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RouteGeometry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', djgeojson.fields.LineStringField()),
            ],
        ),
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spot_name', models.CharField(max_length=100)),
                ('geom', djgeojson.fields.PointField()),
                ('spot_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miroutes.Area')),
            ],
        ),
        migrations.CreateModel(
            name='Wall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wall_name', models.CharField(max_length=100)),
                ('geom', djgeojson.fields.PointField()),
                ('is_active', models.BooleanField(default=False)),
                ('background_img', models.ImageField(blank=True, upload_to=miroutes.models.get_bg_img_upload_path)),
                ('wall_spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miroutes.Spot')),
            ],
        ),
        migrations.CreateModel(
            name='WallView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_dev', models.BooleanField(default=False)),
                ('approach', models.TextField(blank=True, null=True)),
                ('approach_time', models.DurationField(blank=True, null=True)),
                ('exposure', models.IntegerField(blank=True, choices=[(0, b'North'), (1, b'North-East'), (2, b'East'), (3, b'South-East'), (4, b'South'), (5, b'South-West'), (6, b'West'), (7, b'North-West')], null=True)),
                ('children_friendly', models.IntegerField(blank=True, choices=[(1, b'poor'), (2, b'ok'), (3, b'not bad'), (4, b'good'), (5, b'excellent')], null=True)),
                ('bolt_quality', models.IntegerField(blank=True, choices=[(1, b'poor'), (2, b'ok'), (3, b'not bad'), (4, b'good'), (5, b'excellent')], null=True)),
                ('wall_height', models.IntegerField(blank=True, null=True)),
                ('wall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miroutes.Wall')),
            ],
        ),
        migrations.AddField(
            model_name='routegeometry',
            name='on_wallview',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miroutes.WallView'),
        ),
        migrations.AddField(
            model_name='routegeometry',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miroutes.Route'),
        ),
        migrations.AddField(
            model_name='route',
            name='route_spot',
            field=models.ForeignKey(default=None, editable=False, on_delete=django.db.models.deletion.CASCADE, to='miroutes.Spot'),
        ),
        migrations.AddField(
            model_name='route',
            name='route_walls',
            field=models.ManyToManyField(through='miroutes.RouteGeometry', to='miroutes.WallView'),
        ),
        migrations.AddField(
            model_name='area',
            name='area_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miroutes.Country'),
        ),
    ]
