# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 23:06
from __future__ import unicode_literals

from django.db import migrations
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='geom',
            field=djgeojson.fields.PointField(default=dict),
        ),
    ]
